/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: valencia3dartist (https://sketchfab.com/Sebastian.Valencia.Valencia)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/ufo-073c8a70d9434e439a42d9e519340c0b
Title: UFO
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[8158.567, 180.111, 212.613]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Cylinder007_M9L_0.geometry} material={materials.material} position={[0, 0, -0.083]} />
      </group>
      <group position={[8158.567, 266.408, 212.613]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Object017_M7_0.geometry} material={materials.material_1} position={[0, 0, -0.648]} />
      </group>
      <group position={[8158.567, 261.706, 212.613]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Object018_M2_0.geometry} material={materials.material_2} position={[0, 0, -0.618]} />
      </group>
      <group position={[8158.567, 67.344, 212.613]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Object019_M1_0.geometry} material={materials.material_3} position={[0, 0, 0.655]} />
      </group>
      <group position={[8158.567, 225.082, 211.439]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Object020_M1_0.geometry} material={materials.material_3} position={[0, -0.008, -0.378]} />
      </group>
      <group position={[8158.567, 116.765, 211.714]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Object021_M9L_0.geometry} material={materials.material} position={[0, -0.006, 0.331]} />
      </group>
      <group position={[8158.567, 49.407, 212.613]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Object022_M3_0.geometry} material={materials.material_4} position={[0, 0, 0.772]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
