/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: tab1bit0 (https://sketchfab.com/tab1bit0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-8288a85fdf9d48f6a9a9ec6df27d5aa0
Title: ufo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, 0.484, 2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Dome.belt']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Bottom} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Glass.mini']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Bottom.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
